appiumURL=http://127.0.0.1:4723
androidAutomationName=UiAutomator2
androidAppPackage=com.notes.todolist.notebook.checklist.notepad.android.dev
androidAppActivity=ch.android.launcher.LawnchairLauncher
androidAppLocation=/app/NotesLauncher.apk